### ISSUE TITLE
Script dependencies

### ISSUE THREAD

**Issue by AlexValder** [Jummit/godot-package-manager#1]
It's a minor thing, but the script depends on `requests` which isn't a part of standard library. 

![image](https://user-images.githubusercontent.com/43002441/191082367-30e619e2-b18d-47a1-99ae-66c308030d64.png)
![image](https://user-images.githubusercontent.com/43002441/191082406-1117e7b0-2d52-41f4-8edd-973e86ec9d45.png)

System: Windows 10
Python version: Python 3.10.7

In addition, when there's no `godotmodules.txt` file, but there are installed addons, GOPM can't find them.

**Comment by Jummit** [comment]
Thanks for the feedback! Maybe I'll publish a pip package, then the dependency problem goes away and the installation/updating becomes easier.

I currently don't have plans to synchronize with already installed addons, just download them once via the CLI.

**Comment by Jummit** [comment]
The project is now installable as a python package, so requests will be installed automatically.
